name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build-pre-rel]
jobs:
  build:
    name: Build
    #runs-on: SumatraBuilder
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        run: .\doit.bat -ci
